---
layout: cv
title: Bradley Gardner's CV
---

# Bradley Gardner
Software Engineer / Test Lead

<div id="webaddress">
<a href="mailto:bradleydrumgardner@gmail.com">bradleydrumgardner@gmail.com</a>
| <a href="https://www.linkedin.com/in/bradley-gardner-48b25940/">LinkedIn Profile</a>
| +1 (801) 381-0437
</div>

## Summary

Software Engineer with extensive experience in web development, software testing, automation, and team leadership.  
Adept at designing and executing test plans, restructuring defect tracking, and enhancing release processes.

### Specialized in

Test automation, quality assurance leadership, API/UI testing, agile methodologies

### Skills

- Test Planning & Execution (Manual & Automated)  
- API, UI, and Unit Test Automation  
- Agile Development & Scrum Methodologies  
- Defect Tracking & Reporting (Azure DevOps, TestRail)  
- Release Management & Process Improvement  
- Coaching & Mentoring QA Teams

## Education

`Sep 2019 – Dec 2025`  
__Brigham Young University – Idaho__  
- Bachelor's Degree (in progress)

`Sep 2019 – May 2022`  
__Brigham Young University – Idaho__  
- Associates in Applied Technology

`Sep 2019 – May 2021`  
__Brigham Young University – Idaho__  
- Web Development Certificate

`Nov 2015`  
__International Software Testing Qualifications Board (ISTQB)__  
- Certified Tester – Foundation Level Certificate

## Experience

`Apr 2022 – Present`  
__Software Engineer, ThetaCore__, Lehi, Utah  
- Developed and maintained features across 2 web and 1 mobile projects  
- Created and executed both manual and automated test scenarios  
- Managed application release cycles, reducing release time from monthly to bi-weekly  
- Optimized defect tracking process in Azure DevOps, reducing unresolved bugs from 150 to 15

`Sep 2021 – Apr 2022`  
__QA Manager, Vasion__, St. George, Utah  
- Led a team of QA professionals, providing guidance and mentorship  
- Enhanced efficiency and quality standards, leading to faster release cycles  
- Improved technical documentation clarity and completeness  
- Established QA methodologies and contributed to design reviews

`Sep 2018 – Sep 2021`  
__Software
